package waclay-wasi:examples@0.1.0;

interface funcs {
    print-stdout: func(text: string);
    print-stderr: func(text: string);
    read-stdin: func() -> string;
    exit: func();
}

world stdio {
    export funcs;
}
